# Generated by Django 3.1.2 on 2020-10-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_host_or_ip', models.TextField()),
                ('hostname', models.TextField(blank=True)),
                ('vendor', models.TextField(blank=True)),
                ('model', models.TextField(blank=True)),
                ('software', models.TextField(blank=True)),
                ('device_type', models.TextField(blank=True)),
            ],
        ),
    ]
