# Generated by Django 3.1.2 on 2020-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_host_or_ip', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('software', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
