# Generated by Django 3.1.2 on 2020-10-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='seed_host_or_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='software',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
