# Generated by Django 3.1.2 on 2020-10-20 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='When created', null=True)),
                ('changed', models.DateTimeField(blank=True, help_text='Last changed', null=True)),
                ('CustomerName', models.CharField(help_text='Customer Name', max_length=256, unique=True)),
                ('CustomerDescription', models.CharField(blank=True, help_text='Customer Description', max_length=256, null=True)),
                ('primaryContactFirstName', models.CharField(blank=True, help_text='Customer First Name', max_length=256, null=True)),
                ('primaryContactLastName', models.CharField(blank=True, help_text='Customer Last Name', max_length=256, null=True)),
                ('primaryContactEmail', models.EmailField(blank=True, help_text='Contact Email', max_length=256, null=True)),
                ('primaryContactCellPhone', models.CharField(blank=True, help_text='Contact Cell Phone', max_length=256, null=True)),
                ('primaryContactWorkPhone', models.CharField(blank=True, help_text='Contact Work Phone', max_length=256, null=True)),
                ('primaryContactAddress1', models.CharField(blank=True, help_text='Contact Address', max_length=256, null=True)),
                ('primaryContactAddress2', models.CharField(blank=True, help_text='Contact Address2', max_length=256, null=True)),
                ('primaryContactCity', models.CharField(blank=True, help_text='Contact City', max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='When created', null=True)),
                ('changed', models.DateTimeField(blank=True, help_text='Last changed', null=True)),
                ('username', models.CharField(help_text='Login username', max_length=256)),
                ('password', models.CharField(blank=True, help_text='Login password', max_length=256, null=True)),
                ('enable_pass', models.CharField(blank=True, help_text='Enable password (if needed)', max_length=256, null=True)),
                ('description', models.CharField(blank=True, default='', help_text='Short description', max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
